name: NSE OI Collector

on:
  schedule:
    # Runs every 5 minutes from 03:30 to 10:00 UTC (9:00 - 15:30 IST)
    # Format: minute hour day month day-of-week
    # 1. Start at 03:25 UTC (8:55 AM IST) and run every 5 mins until 03:55 UTC (9:25 AM IST)
    - cron: '25,30,35,40,45,50,55 3 * * 1-5'
    # 2. Run every 5 mins from 04:00 UTC (9:30 AM IST) until 10:00 UTC (15:30 PM IST)
    - cron: '*/5 4-10 * * 1-5'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        item: 
          - { name: "nifty50", symbol: "nse50_opt" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip' # Will cache python packages like pandas, requests for subsequent runs

      - name: Install dependencies
        run: pip install -r requirements_data.txt

      - name: Run Scraper
        env:
          index_symbol: ${{ matrix.item.symbol }}
          index_name: ${{ matrix.item.name }}
        run: python nse_scraper.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add optionOIData/
          git commit -m "Updated data for index: ${{ matrix.item.name }} $(date)" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
